### ISSUE TITLE
`wc-env-manager pull` fails

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_env_manager#15]
Trace below. The first 2 lines starting `config` are produced by my debugging code.

    $ wc-env-manager pull

    config['repo_unsquashed'] karrlab/wc_env_dependencies_unsquashed
    config['tags'] ['latest', '0.0.51']
    Traceback (most recent call last):
      File "/anaconda3/lib/python3.6/site-packages/docker/api/client.py", line 229, in _raise_for_status
        response.raise_for_status()
      File "/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/karrlab/wc_env_dependencies_unsquashed:0.0.51/json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/anaconda3/bin/wc-env-manager", line 10, in <module>
        sys.exit(main())
      File "/anaconda3/lib/python3.6/site-packages/wc_env_manager/__main__.py", line 277, in main
        app.run()
      File "/anaconda3/lib/python3.6/site-packages/cement/core/foundation.py", line 916, in run
        return_val = self.controller._dispatch()
      File "/anaconda3/lib/python3.6/site-packages/cement/ext/ext_argparse.py", line 806, in _dispatch
        return func()
      File "/anaconda3/lib/python3.6/site-packages/wc_env_manager/__main__.py", line 236, in pull
        mgr.pull_image(config['repo_unsquashed'], config['tags'])
      File "/anaconda3/lib/python3.6/site-packages/wc_env_manager/core.py", line 491, in pull_image
        image = self._docker_client.images.pull(image_repo, tag=tag)
      File "/anaconda3/lib/python3.6/site-packages/docker/models/images.py", line 415, in pull
        repository, tag, '@' if tag.startswith('sha256:') else ':'
      File "/anaconda3/lib/python3.6/site-packages/docker/models/images.py", line 295, in get
        return self.prepare_model(self.client.api.inspect_image(name))
      File "/anaconda3/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
        return f(self, resource_id, *args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/docker/api/image.py", line 245, in inspect_image
        self._get(self._url("/images/{0}/json", image)), True
      File "/anaconda3/lib/python3.6/site-packages/docker/api/client.py", line 235, in _result
        self._raise_for_status(response)
      File "/anaconda3/lib/python3.6/site-packages/docker/api/client.py", line 231, in _raise_for_status
        raise create_api_error_from_http_exception(e)
      File "/anaconda3/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
        raise cls(e, response=response, explanation=explanation)
    docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: karrlab/wc_env_dependencies_unsquashed:0.0.51: No such image: karrlab/wc_env_dependencies_unsquashed:0.0.51")

**Comment by artgoldberg** [comment]
The tag `latest` by itself also fails, so the tag isn't the problem:

    $ wc-env-manager pull

    config['repo_unsquashed'] karrlab/wc_env_dependencies_unsquashed
    config['tags'] ['latest']
    ^[[BTraceback (most recent call last):
      File "/anaconda3/lib/python3.6/site-packages/docker/api/client.py", line 229, in _raise_for_status
        response.raise_for_status()
      File "/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/karrlab/wc_env_dependencies:latest/json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/anaconda3/bin/wc-env-manager", line 10, in <module>
        sys.exit(main())
      File "/anaconda3/lib/python3.6/site-packages/wc_env_manager/__main__.py", line 277, in main
        app.run()
      File "/anaconda3/lib/python3.6/site-packages/cement/core/foundation.py", line 916, in run
        return_val = self.controller._dispatch()
      File "/anaconda3/lib/python3.6/site-packages/cement/ext/ext_argparse.py", line 806, in _dispatch
        return func()
      File "/anaconda3/lib/python3.6/site-packages/wc_env_manager/__main__.py", line 239, in pull
        mgr.pull_image(config['repo'], config['tags'])
      File "/anaconda3/lib/python3.6/site-packages/wc_env_manager/core.py", line 491, in pull_image
        image = self._docker_client.images.pull(image_repo, tag=tag)
      File "/anaconda3/lib/python3.6/site-packages/docker/models/images.py", line 415, in pull
        repository, tag, '@' if tag.startswith('sha256:') else ':'
      File "/anaconda3/lib/python3.6/site-packages/docker/models/images.py", line 295, in get
        return self.prepare_model(self.client.api.inspect_image(name))
      File "/anaconda3/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
        return f(self, resource_id, *args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/docker/api/image.py", line 245, in inspect_image
        self._get(self._url("/images/{0}/json", image)), True
      File "/anaconda3/lib/python3.6/site-packages/docker/api/client.py", line 235, in _result
        self._raise_for_status(response)
      File "/anaconda3/lib/python3.6/site-packages/docker/api/client.py", line 231, in _raise_for_status
        raise create_api_error_from_http_exception(e)
      File "/anaconda3/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
        raise cls(e, response=response, explanation=explanation)
    docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: karrlab/wc_env_dependencies:latest: No such image: karrlab/wc_env_dependencies:latest")

**Comment by jonrkarr** [comment]
May be a DockerHub/Docker API error.
These images/tags exist. See https://hub.docker.com/r/karrlab/wc_env_dependencies_unsquashed/tags.

**Comment by artgoldberg** [comment]
Explicit `docker pull` works:

    $ docker pull karrlab/wc_env_dependencies:latest
    latest: Pulling from karrlab/wc_env_dependencies
    d54baa01f729: Pull complete 
    49b4e88830fa: Pull complete 
    Digest: sha256:f42b2996d9265a9360ea19aa213e756e9c0fe550221cdeb8bdf00f1cd3ec738b
    Status: Downloaded newer image for karrlab/wc_env_dependencies:latest
    docker.io/karrlab/wc_env_dependencies:latest

**Comment by artgoldberg** [comment]
I couldn't find an API error or Docker logs. 
The API (1.35) and the Engine: 19.03.1 are [listed as compatible](https://docs.docker.com/develop/sdk/).

Here's the Anaconda Docker package installation information:
[conda_docker_info.txt](https://github.com/KarrLab/wc_env_manager/files/3522920/conda_docker_info.txt)

**Comment by jonrkarr** [comment]
The issue looks like an error with the REST API for DockerHub which is wrapped by the PyPI docker package. 

Could be due to the upgrade of the pypi docker package (version 4 was released in May). Did you try v 3.7.3?

**Comment by artgoldberg** [comment]
I made `wc-env-manager pull` work by installing `docker-py` in `conda`:

Initially:

    $ conda list docker
    # packages in environment at /anaconda3:
    #
    # Name                    Version                   Build  Channel
    docker                    3.5.0                    pypi_0    pypi
    docker-pycreds            0.3.0                    pypi_0    pypi
    docker-squash             1.0.7                    pypi_0    pypi

Update:

    $ conda install docker-py=3.5.1
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Collecting package metadata (repodata.json): done
    Solving environment: / 
    The environment is inconsistent, please check the package plan carefully
    The following packages are causing the inconsistency:

      - defaults/osx-64::blaze==0.11.3=py36_0
      - defaults/osx-64::anaconda==2019.07=py36_0
      - defaults/osx-64::numba==0.45.0=py36h6440ff4_0
    done

    ## Package Plan ##
      environment location: /anaconda3

      added / updated specs:
        - docker-py=3.5.1

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        _anaconda_depends-2019.03  |           py36_0           6 KB
        anaconda-custom            |           py36_1           3 KB
        appdirs-1.4.3              |   py36h28b3542_0          15 KB
        ca-certificates-2019.5.15  |                1         133 KB
        certifi-2019.6.16          |           py36_1         155 KB
        docker-py-3.5.1            |        py36_1001         160 KB
        docker-pycreds-0.4.0       |             py_0          14 KB
        tbb-2019.4                 |       h04f5b5a_0         147 KB
        websocket-client-0.56.0    |           py36_0          61 KB
        ------------------------------------------------------------
                                               Total:         695 KB

    The following NEW packages will be INSTALLED:

      _anaconda_depends  pkgs/main/osx-64::_anaconda_depends-2019.03-py36_0
      appdirs            pkgs/main/osx-64::appdirs-1.4.3-py36h28b3542_0
      docker-py          pkgs/main/osx-64::docker-py-3.5.1-py36_1001
      docker-pycreds     pkgs/main/noarch::docker-pycreds-0.4.0-py_0
      tbb                pkgs/main/osx-64::tbb-2019.4-h04f5b5a_0
      websocket-client   pkgs/main/osx-64::websocket-client-0.56.0-py36_0

    The following packages will be UPDATED:

      ca-certificates                               2019.5.15-0 --> 2019.5.15-1
      certifi                                  2019.6.16-py36_0 --> 2019.6.16-py36_1

    The following packages will be DOWNGRADED:

      anaconda                                   2019.07-py36_0 --> custom-py36_1

    Proceed ([y]/n)? y

    Downloading and Extracting Packages
    websocket-client-0.5 | 61 KB     | ####################### | 100% 
    ca-certificates-2019 | 133 KB    | ####################### | 100% 
    docker-py-3.5.1      | 160 KB    | ####################### | 100% 
    certifi-2019.6.16    | 155 KB    | ####################### | 100% 
    _anaconda_depends-20 | 6 KB      | ####################### | 100% 
    tbb-2019.4           | 147 KB    | ####################### | 100% 
    appdirs-1.4.3        | 15 KB     | ####################### | 100% 
    docker-pycreds-0.4.0 | 14 KB     | ####################### | 100% 
    anaconda-custom      | 3 KB      | ####################### | 100% 
    Preparing transaction: done
    Verifying transaction: done
    Executing transaction: done

Result:

    $ conda list docker
    # packages in environment at /anaconda3:
    # Name                    Version                   Build  Channel
    docker                    3.5.0                    pypi_0    pypi
    docker-py                 3.5.1                 py36_1001  
    docker-pycreds            0.3.0                    pypi_0    pypi
    docker-squash             1.0.7                    pypi_0    pypi

Removed wc_env_dependencies images:

    $ docker image ls
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
    circleci/postgres   11.2-alpine-ram     9bba4a631f6d        3 months ago        70.8MB
    karrlab/wc_env      0.0.51              3d35a1beb777        4 months ago        5.81GB
    karrlab/wc_env      latest              3d35a1beb777        4 months ago        5.81GB
    $

Try wc-env-manager:

    $ wc-env-manager pull
    $ docker image ls
    REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
    circleci/postgres                        11.2-alpine-ram     9bba4a631f6d        3 months ago        70.8MB
    karrlab/wc_env                           0.0.51              3d35a1beb777        4 months ago        5.81GB
    karrlab/wc_env                           latest              3d35a1beb777        4 months ago        5.81GB
    karrlab/wc_env_dependencies              latest              953edb5668b3        4 months ago        5.72GB
    karrlab/wc_env_dependencies_unsquashed   latest              d4322c96ccd6        4 months ago        6.52GB
